# permissions for end users to view clusterscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dariia-test
    app.kubernetes.io/managed-by: kustomize
  name: dariia-clusterscan-viewer-role
rules:
- apiGroups:
  - dariia.example.com
  resources:
  - clusterscans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dariia.example.com
  resources:
  - clusterscans/status
  verbs:
  - get
