apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2024-05-21T21:14:04Z","generation":1,"labels":{"app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"cluster-scan-controller","control-plane":"controller-manager"},"name":"cluster-scan-controller-controller-manager","namespace":"cluster-scan-controller-system","resourceVersion":"37286","uid":"9844c64e-3c69-4254-9562-b9093f6c19af"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"control-plane":"controller-manager"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/default-container":"manager"},"creationTimestamp":null,"labels":{"control-plane":"controller-manager"}},"spec":{"containers":[{"args":["--leader-elect","--health-probe-bind-address=:8081","--metrics-bind-address=0"],"command":["/manager"],"image":"balenalib/armv7hf-alpine","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8081,"scheme":"HTTP"},"initialDelaySeconds":15,"periodSeconds":20,"successThreshold":1,"timeoutSeconds":1},"name":"manager","readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/readyz","port":8081,"scheme":"HTTP"},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"500m","memory":"128Mi"},"requests":{"cpu":"10m","memory":"64Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"runAsNonRoot":true},"serviceAccount":"cluster-scan-controller-controller-manager","serviceAccountName":"cluster-scan-controller-controller-manager","terminationGracePeriodSeconds":10}}},"status":{"conditions":[{"lastTransitionTime":"2024-05-21T21:14:04Z","lastUpdateTime":"2024-05-21T21:14:04Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2024-05-22T23:53:49Z","lastUpdateTime":"2024-05-23T00:02:51Z","message":"ReplicaSet \"cluster-scan-controller-controller-manager-5b64c4f8d8\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":1,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-05-23T00:13:37Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster-scan-controller
    control-plane: controller-manager
  name: cluster-scan-controller-controller-manager
  namespace: cluster-scan-controller-system
  resourceVersion: "38235"
  uid: 0485c0e0-ac35-41d0-98cd-631c652a919c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      creationTimestamp: null
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=0
        command:
        - /manager
        image: balenalib/armv7hf-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
      serviceAccount: cluster-scan-controller-controller-manager
      serviceAccountName: cluster-scan-controller-controller-manager
      terminationGracePeriodSeconds: 10
status:
  conditions:
  - lastTransitionTime: "2024-05-23T00:13:37Z"
    lastUpdateTime: "2024-05-23T00:13:37Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-05-23T00:13:37Z"
    lastUpdateTime: "2024-05-23T00:13:37Z"
    message: ReplicaSet "cluster-scan-controller-controller-manager-c49756775" is
      progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
